development:
  sessions:
    default:
      hosts:
        - localhost
      database: ada_development

test:
  sessions:
    default:
      hosts:
        - localhost
      database: ada_development

# set these environment variables on your prod server
production:
  sessions:
    default:
      host: <%= ENV['MONGOID_HOST'] %>
      port: <%= ENV['MONGOID_PORT'] %>
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      database: <%= ENV['MONGOID_DATABASE'] %>